export const routeConstants = {
  HOME: "/",
  CATEGORIES: "/categories",
  PRODUCTS_CREATE: "/products/create",
  TOURS: "/tours",
  MY_TOURS: "/my-tours",
  LANDSCAPES: "/landscapes",
  CATEGORY_PAGE: "/categories/:categoryId",
  CREATE_PRODUCT: "/products/create",
  PRODUCT_DETAILS: "/products/:productId",
  PRODUCTS: "/products",
  ANALYTICS: "/analytics",
  BRANDS_AUTOS: "/brands/:brandId/autos",
  BRANDS: "/brands",
  BRANDS_AUTOS_DETAILS: "/brands/:brandId/autos/:autoId",
  TOUR_DETAILS: "/tour/:tourId",
  BOOK_TOUR: "/book/tour/:tourId",
};
