import type { Category } from "./types";

export const categoriesData: Category[] = [
  {
    id: "engineering",
    name: "Engineering & Development",
    description: "Tools for software development",
    subCategories: [
      {
        id: "frontend",
        name: "Frontend Development",
        description: "UI/UX tools and frameworks",
        slug: "frontend-development",
        icon: "🎨",
      },
      {
        id: "backend",
        name: "Backend Development",
        description: "Server-side tools and APIs",
        slug: "backend-development",
        icon: "⚙️",
      },
      {
        id: "mobile",
        name: "Mobile Development",
        description: "iOS and Android development",
        slug: "mobile-development",
        icon: "📱",
      },
      {
        id: "devops",
        name: "DevOps & Infrastructure",
        description: "Deployment and monitoring tools",
        slug: "devops-infrastructure",
        icon: "🚀",
      },
    ],
  },
  {
    id: "design",
    name: "Design & Creative",
    description: "Creative tools and resources",
    subCategories: [
      {
        id: "ui-design",
        name: "UI/UX Design",
        description: "Interface design tools",
        slug: "ui-ux-design",
        icon: "🎯",
      },
      {
        id: "graphic-design",
        name: "Graphic Design",
        description: "Visual design tools",
        slug: "graphic-design",
        icon: "🖼️",
      },
      {
        id: "prototyping",
        name: "Prototyping",
        description: "Rapid prototyping tools",
        slug: "prototyping",
        icon: "🔧",
      },
    ],
  },
  {
    id: "productivity",
    name: "Productivity & Business",
    description: "Tools to boost productivity",
    subCategories: [
      {
        id: "project-management",
        name: "Project Management",
        description: "Organize and track projects",
        slug: "project-management",
        icon: "📊",
      },
      {
        id: "collaboration",
        name: "Team Collaboration",
        description: "Communication and teamwork",
        slug: "team-collaboration",
        icon: "👥",
      },
      {
        id: "analytics",
        name: "Analytics & Data",
        description: "Data analysis and insights",
        slug: "analytics-data",
        icon: "📈",
      },
    ],
  },
  {
    id: "marketing",
    name: "Marketing & Sales",
    description: "Grow your business",
    subCategories: [
      {
        id: "social-media",
        name: "Social Media",
        description: "Social media management",
        slug: "social-media",
        icon: "📢",
      },
      {
        id: "email-marketing",
        name: "Email Marketing",
        description: "Email campaigns and automation",
        slug: "email-marketing",
        icon: "📧",
      },
      {
        id: "seo",
        name: "SEO & Content",
        description: "Search optimization tools",
        slug: "seo-content",
        icon: "🔍",
      },
    ],
  },
  {
    id: "engineering",
    name: "Engineering & Development",
    description: "Tools for software development",
    subCategories: [
      {
        id: "frontend",
        name: "Frontend Development",
        description: "UI/UX tools and frameworks",
        slug: "frontend-development",
        icon: "🎨",
      },
      {
        id: "backend",
        name: "Backend Development",
        description: "Server-side tools and APIs",
        slug: "backend-development",
        icon: "⚙️",
      },
      {
        id: "mobile",
        name: "Mobile Development",
        description: "iOS and Android development",
        slug: "mobile-development",
        icon: "📱",
      },
      {
        id: "devops",
        name: "DevOps & Infrastructure",
        description: "Deployment and monitoring tools",
        slug: "devops-infrastructure",
        icon: "🚀",
      },
    ],
  },
  {
    id: "design",
    name: "Design & Creative",
    description: "Creative tools and resources",
    subCategories: [
      {
        id: "ui-design",
        name: "UI/UX Design",
        description: "Interface design tools",
        slug: "ui-ux-design",
        icon: "🎯",
      },
      {
        id: "graphic-design",
        name: "Graphic Design",
        description: "Visual design tools",
        slug: "graphic-design",
        icon: "🖼️",
      },
      {
        id: "prototyping",
        name: "Prototyping",
        description: "Rapid prototyping tools",
        slug: "prototyping",
        icon: "🔧",
      },
    ],
  },
];
