import { http } from "msw";

export const handlers = [
  http.get(/\/api\/products/, () => {
    return new Response(
      JSON.stringify({
        data: [
          {
            _id: "1",
            name: "LaunchPad Pro",
            slug: "launchpad-pro",
            description: "An AI-powered product launch platform",
            image: "https://example.com/images/launchpad.jpg",
            tags: ["AI", "Marketing", "Product Launch"],
            website: "https://launchpadpro.com",
            votesCount: 245,
            launchDate: { type: "date", required: true },
            createdAt: "2025-05-15T10:30:00Z",
            updatedAt: "2025-06-01T14:22:00Z",
            category: {
              _id: "cat1",
              name: "Marketing Tools",
              slug: "marketing-tools",
              parentId: "",
              description: "Tools to help with product marketing",
              image: "https://example.com/images/marketing.jpg",
              createdAt: "2025-01-10T08:15:00Z",
              updatedAt: "2025-01-10T08:15:00Z",
            },
          },
          {
            _id: "2",
            name: "DevFlow",
            slug: "devflow",
            description: "Developer workflow automation suite",
            image: "https://example.com/images/devflow.jpg",
            tags: ["Development", "Automation", "Productivity"],
            website: "https://devflow.io",
            votesCount: 189,
            launchDate: { type: "date", required: true },
            createdAt: "2025-04-22T09:45:00Z",
            updatedAt: "2025-05-30T16:10:00Z",
            category: {
              _id: "cat2",
              name: "Development Tools",
              slug: "dev-tools",
              parentId: "",
              description: "Tools for software developers",
              image: "https://example.com/images/devtools.jpg",
              createdAt: "2025-01-12T11:30:00Z",
              updatedAt: "2025-01-12T11:30:00Z",
            },
          },
          {
            _id: "3",
            name: "AnalyticsPro",
            slug: "analytics-pro",
            description: "Advanced analytics platform for businesses",
            image: "https://example.com/images/analyticspro.jpg",
            tags: ["Analytics", "Business Intelligence", "Data"],
            website: "https://analyticspro.dev",
            votesCount: 312,
            launchDate: { type: "date", required: true },
            createdAt: "2025-03-18T14:20:00Z",
            updatedAt: "2025-06-05T09:15:00Z",
            category: {
              _id: "cat3",
              name: "Data Tools",
              slug: "data-tools",
              parentId: "",
              description: "Tools for data analysis and visualization",
              image: "https://example.com/images/datatools.jpg",
              createdAt: "2025-01-15T10:45:00Z",
              updatedAt: "2025-01-15T10:45:00Z",
            },
          },
          {
            _id: "4",
            name: "DesignMaster",
            slug: "design-master",
            description: "All-in-one design toolkit for modern designers",
            image: "https://example.com/images/designmaster.jpg",
            tags: ["Design", "UI/UX", "Creativity"],
            website: "https://designmaster.app",
            votesCount: 178,
            launchDate: { type: "date", required: true },
            createdAt: "2025-05-02T11:10:00Z",
            updatedAt: "2025-06-03T15:40:00Z",
            category: {
              _id: "cat4",
              name: "Design Tools",
              slug: "design-tools",
              parentId: "",
              description: "Tools for designers and creatives",
              image: "https://example.com/images/designtools.jpg",
              createdAt: "2025-01-18T13:20:00Z",
              updatedAt: "2025-01-18T13:20:00Z",
            },
          },
          {
            _id: "5",
            name: "SecureVault",
            slug: "secure-vault",
            description: "Advanced security platform for sensitive data",
            image: "https://example.com/images/securevault.jpg",
            tags: ["Security", "Privacy", "Data Protection"],
            website: "https://securevault.io",
            votesCount: 267,
            launchDate: { type: "date", required: true },
            createdAt: "2025-04-10T08:30:00Z",
            updatedAt: "2025-06-02T11:25:00Z",
            category: {
              _id: "cat5",
              name: "Security Tools",
              slug: "security-tools",
              parentId: "",
              description: "Tools for data security and protection",
              image: "https://example.com/images/securitytools.jpg",
              createdAt: "2025-01-20T09:50:00Z",
              updatedAt: "2025-01-20T09:50:00Z",
            },
          },
        ],
        total: 5,
        page: 1,
        pageSize: 5,
        totalPages: 1,
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  }),
];
